//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application.web.Areas.Registro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COMPROBANTE_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_COMPROBANTE_CAB()
        {
            this.TB_COMPROBANTE_DET = new HashSet<TB_COMPROBANTE_DET>();
        }
    
        public string estab_serie { get; set; }
        public Nullable<System.DateTime> cabe_fecha { get; set; }
        public string cabe_ticket { get; set; }
        public Nullable<System.DateTime> cabe_hora { get; set; }
        public string cod_estab { get; set; }
        public int cod_comp { get; set; }
        public string usu_docid_codigo { get; set; }
        public string login_user { get; set; }
        public string Nro_Fua { get; set; }
        public Nullable<decimal> Mont_Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_COMPROBANTE_DET> TB_COMPROBANTE_DET { get; set; }
    }
}
